package cmd

//StateFips is a mapping of state names (uppercase) to FIPS codes
var StateFips = map[string]int{
	"ALABAMA":              1,
	"ALASKA":               2,
	"ARIZONA":              4,
	"ARKANSAS":             5,
	"CALIFORNIA":           6,
	"COLORADO":             8,
	"CONNECTICUT":          9,
	"DELAWARE":             10,
	"DISTRICT OF COLUMBIA": 11,
	"FLORIDA":              12,
	"GEORGIA":              13,
	"HAWAII":               15,
	"IDAHO":                16,
	"ILLINOIS":             17,
	"INDIANA":              18,
	"IOWA":                 19,
	"KANSAS":               20,
	"KENTUCKY":             21,
	"LOUISIANA":            22,
	"MAINE":                23,
	"MARYLAND":             24,
	"MASSACHUSETTS":        25,
	"MICHIGAN":             26,
	"MINNESOTA":            27,
	"MISSISSIPPI":          28,
	"MISSOURI":             29,
	"MONTANA":              30,
	"NEBRASKA":             31,
	"NEVADA":               32,
	"NEW HAMPSHIRE":        33,
	"NEW JERSEY":           34,
	"NEW MEXICO":           35,
	"NEW YORK":             36,
	"NORTH CAROLINA":       37,
	"NORTH DAKOTA":         38,
	"OHIO":                 39,
	"OKLAHOMA":             40,
	"OREGON":               41,
	"PENNSYLVANIA":         42,
	"RHODE ISLAND":         44,
	"SOUTH CAROLINA":       45,
	"SOUTH DAKOTA":         46,
	"TENNESSEE":            47,
	"TEXAS":                48,
	"UTAH":                 49,
	"VERMONT":              50,
	"VIRGINIA":             51,
	"WASHINGTON":           53,
	"WEST VIRGINIA":        54,
	"WISCONSIN":            55,
	"WYOMING":              56,
	"AMERICAN SAMOA":       60,
	"GUAM":                 66,
	"PUERTO RICO":          72,
	"US VIRGIN ISLANDS":    78,
}

//StaeAbr maps from 2 letter appreviations to state names
var StateAbr = map[string]string{
	"AA": "Armed Forces (the) Americas",
	"AB": "Alberta",
	"AE": "Armed Forces Europe",
	"AK": "Alaska",
	"AL": "Alabama",
	"AP": "Armed Forces Pacific",
	"AR": "Arkansas",
	"AS": "American Samoa",
	"AZ": "Arizona",
	"BC": "British Columbia",
	"CA": "California",
	"CD": "Canada",
	"CO": "Colorado",
	"CT": "Connecticut",
	"DC": "Dist. Of Columbia",
	"DE": "Delaware",
	"FF": "Foreign Countries",
	"FL": "Florida",
	"GA": "Georgia",
	"GU": "Guam",
	"HI": "Hawaii",
	"IA": "Iowa",
	"ID": "Idaho",
	"IL": "Illinois",
	"IN": "Indiana",
	"KS": "Kansas",
	"KY": "Kentucky",
	"LA": "Louisiana",
	"MA": "Massachusetts",
	"MB": "Manitoba",
	"MD": "Maryland",
	"ME": "Maine",
	"MI": "Michigan",
	"MN": "Minnesota",
	"MO": "Missouri",
	"MS": "Mississippi",
	"MT": "Montana",
	"MX": "Mexico",
	"NB": "New Brunswick",
	"NC": "North Carolina",
	"ND": "North Dakota",
	"NE": "Nebraska",
	"NH": "New Hampshire",
	"NJ": "New Jersey",
	"NL": "Newfoundland and Labrador",
	"NM": "New Mexico",
	"NS": "Nova Scotia",
	"NT": "Northwest Territories",
	"NU": "Nunavut",
	"NV": "Nevada",
	"NY": "New York",
	"OH": "Ohio",
	"OK": "Oklahoma",
	"ON": "Ontario",
	"OR": "Oregon",
	"PA": "Pennsylvania",
	"PE": "Prince Edward Island",
	"PR": "Puerto Rico",
	"QC": "Quebec",
	"RI": "Rhode Island",
	"SC": "South Carolina",
	"SD": "South Dakota",
	"SK": "Saskatchewan",
	"TN": "Tennessee",
	"TT": "Trust Territory",
	"TX": "Texas",
	"UN": "Unknown",
	"UT": "Utah",
	"VA": "Virginia",
	"VI": "Virgin Islands",
	"VT": "Vermont",
	"WA": "Washington",
	"WI": "Wisconsin",
	"WV": "West Virginia",
	"WY": "Wyoming",
	"YT": "Yukon",
}
